<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CS1591;CS1573</NoWarn>
    <RootNamespace>Blun.MultiRaft.Grpc.Benchmarks</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Blun.MultiRaft.Grpc/Blun.MultiRaft.Grpc.csproj" />
  </ItemGroup>

</Project>
