<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net11.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="K4os.Compression.LZ4" />
    <PackageReference Include="K4os.Compression.LZ4.Streams" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Blun.MultiRaft.Wal/Blun.MultiRaft.Wal.csproj" />
    <ProjectReference Include="../../src/Blun.MultiRaft/Blun.MultiRaft.csproj" />
  </ItemGroup>

</Project>
